apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bj49ttz6n-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bj49ttz6n-java-quarkus-gitops